sudo: false

language: scala
scala:
  - 2.11.7

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

services:
  - docker

before_install:  
  - sudo apt-get update
  - sudo apt-get install docker-engine

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

after_success:
  - pip install --user codecov && codecov
