server:
  port: 8080
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
nakadi:
  stream:
    timeoutMs: 31536000000 # 1 year :-P
  kafka:
    poll:
      timeoutMs: 100
    connectionString: 127.0.0.1:9092
  zookeeper:
    connectionString: 127.0.0.1:2181
  oauth2:
    enabled: true
    tokenInfoUri: https://auth.zalando.com/oauth2/tokeninfo
    clientId: stups_aruha-event-store-poc